spring:
  application:
    name: myContact

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mycontact?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

  # Hibernate sẽ không tự động thay đổi schema, vì bạn đang quản lý nó ngoài ứng dụng.
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # Định dạng SQL cho dễ đọc
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080

# Profiles configuration
#spring.profiles.active: ${SPRING_PROFILES_ACTIVE:dev}

# Sự khác nhau của cấu trúc cấu hình application.properties và application.yml
# - .properties: cấu trúc dạng key=value
# - .yml (YAML): cấu trúc phân cấp bằng thụt lề, dễ nhìn và dễ tổ chức hơn
